services:
  db:
    build: ./db
    # コンテナ名を設定
    container_name: "todo_db"
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
    volumes:
      # データ永続化
      - ./data:/var/lib/mysql
    ports:
      - 13306:${DBPORT}
    # ヘルスチェック
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  backend:
    build: ./backend
    container_name: "todo_backend"
    environment:
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBHOST: db # dbサービス名
      DBPORT: ${DBPORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    container_name: "todo_frontend"
    depends_on:
      - backend
    ports:
      - "3000:3000"
